-- NECESITO UNA BASE DE DATOS PARA ALMACENAR LOS ALUMNOS DE MI COLEGIO
-- MI COLEGIO ES SOLO DE PRIMARIA Y SOLAMENTE QUIERO ALMACENAR
-- EL ALUMNO CON SU INFORMACION QUE SERIA NOMBRE,APE PATERNO, APELLIDO MATERNO, CORREO
-- NUMERO DE EMEREGENCIA Y DE CADA SECCION ALAMCENAR SU NOMBRE (ABC) Y SU,
-- UBICACION (PRIMER PISO, SEGUNDO PISO,SOTANO)
-- POR SI ACASO EL ALUMNO PUEDE CAMBIAR DE SECCCION  CADA AÑO
-- ALMACENAR SU HISTORIAL

CREATE DATABASE colegios;

USE colegios;

CREATE TABLE IF NOT EXISTS alumnos(
	id INT PRIMARY KEY AUTO_INCREMENT,
    apellido_paterno VARCHAR(50) NOT NULL,
    apellido_materno VARCHAR(50),
    correo VARCHAR(50) NOT NULL,
    numero de emergencia VARCHAR(20) NOT NULL,
);




CREATE TABLE IF NOT EXISTS niveles(
	id INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS alumnos_niveles(
	id INT PRIMARY KEY AUTO_INCREMENT
);