# Generated by Django 4.0.4 on 2022-04-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_creacion_tabla_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
