-- INSERTAR DATA
USE prueba;
-- EN BASE DATOS Y LENGUAJES DE PROGRAMACION SE UTILIZA EL ISO 8601
INSERT INTO vacunaciones(nombre,estado,fecha_vencimiento,procedencia,lote) VALUES
					('PFIZER', true, '2022-08-16', 'USA', '123JKL'),
                    ('SINOFARM', true, '2022-10-10', 'CHINA', 'VXCVXC'),
                    ('MODERNA', true, '2022-09-14', 'USA', 'ZXCZXC'),
                     ('SPUTNIK', FALSE, '2022-10-04', 'RUSIA', 'HGJKHJFG');

INSERT INTO VACUNATORIOS (nombre,latitud,longitud,direccion,horario_atencion,foto,vacuna_id) values
				  ('CAMINO REAL', 14.121, -21.121, 'AV GIRASOL 115', 'LUN-VIE 07:00 - 15:00', null, 1),
				  ('HOSP. GNRAL.', 17.521, 11.1891, 'AV CIRCUNVALACION S/N', 'LUN-VIE 07:00 - 15:00', 'hospital.jpg', 2),
				  ('POSTA CERRO AZUL', 11.258, 67.447, 'AAHH LOS QUERUBINES LOTE 3 MZ J', 'LUN-SAB 07:00 - 15:00', 'foto01.png', 1),
				  ('ESTADIO LOS PALITOS', 24.121, -21.121, 'CALLE ESPINOSA 1115', 'LUN-MIE-VIE 07:00 - 15:00', 'est0001.jpg', 3),
				  ('PLAZA DEL AMOR', 4.116, -21.121, 'AV DE LOS HEROES ANONIMOS S/N', 'LUN-VIE 07:00 - 15:00', null, 1);
                     


-- MOSTRAR TODOS LOS NOMBRES DE LAS VACUNAS
-- MOSTTRAR LAS VACUNAS DE PROCEDENCIA USA
-- MOSTRAR LAS QUE NO SEAN DE USA
-- MOSTRAR LAS VACUNAS QUE EN SU LOTE TENGAN LOS DIGITOS 'XC'
-- MOSTRAR LOS VACUNATORIOS QUE TENGAN HORARIO DE ATENCION LOS DIAS MIERCOLES

SELECT NOMBRE FROM VACUNACIONES;
SELECT PROCEDENCIA FROM VACUNACIONES WHERE PROCEDENCIA='USA';
SELECT PROCEDENCIA FROM VACUNACIONES WHERE PROCEDENCIA<>'USA';
SELECT LOTE FROM VACUNACIONES WHERE LOTE LIKE '%xc';
select * from vacunatorios WHERE horario_atencion LIKE '%MIE';
        